/*
Minimum cost to reach the top of the floor by climbing stairs
https://www.geeksforgeeks.org/minimum-cost-to-reach-the-top-of-the-floor-by-climbing-stairs/

Given N non-negative integers which signifies the cost of the moving from each stair. 
Paying the cost at i-th step, you can either climb one or two steps. 
Given that one can start from the 0-the step or 1-the step, 
the task is to find the minimum cost to reach the top of the floor(N+1) by climbing N stairs.

Examples:

Input: a[] = { 16, 19, 10, 12, 18 }
Output: 31
Start from 19 and then move to 12. 

Input: a[] = {2, 5, 3, 1, 7, 3, 4}
Output: 9 
2->3->1->3

*/